services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: search-name-client
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge